{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 144,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of networkx.classes.graphviews failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: subgraph_view() requires a code object with 5 free vars, not 0\n",
      "]\n",
      "[autoreload of networkx.generators.expanders failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/networkx/generators/expanders.py\", line 215, in <module>\n",
      "    @nx.utils.decorators.np_random_state(\"seed\")\n",
      "AttributeError: module 'networkx.utils' has no attribute 'decorators'\n",
      "]\n",
      "[autoreload of networkx failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/networkx/__init__.py\", line 23, in <module>\n",
      "    config = utils.backends._set_configs_from_environment()\n",
      "AttributeError: module 'networkx.utils' has no attribute 'backends'\n",
      "]\n",
      "[autoreload of numpy._core.numeric failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/_core/numeric.py\", line 13, in <module>\n",
      "    from .multiarray import (\n",
      "ImportError: cannot import name '_get_promotion_state' from 'numpy._core.multiarray' (/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/_core/multiarray.py)\n",
      "]\n",
      "[autoreload of numpy failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/__init__.py\", line 295, in <module>\n",
      "    _core.getlimits._register_known_types()\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/_core/getlimits.py\", line 230, in _register_known_types\n",
      "    with numeric.errstate(all='ignore'):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/_core/_ufunc_config.py\", line 419, in __enter__\n",
      "    extobj = _make_extobj(\n",
      "TypeError: python object must be callable or have a callable write method\n",
      "]\n",
      "[autoreload of numpy.testing._private.utils failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/testing/_private/utils.py\", line 58, in <module>\n",
      "    HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64\n",
      "AttributeError: module 'numpy.linalg' has no attribute '_umath_linalg'\n",
      "]\n",
      "[autoreload of numpy.testing failed: Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/extensions/autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 619, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/testing/__init__.py\", line 17, in <module>\n",
      "    _private.utils.__all__ + ['TestCase', 'overrides']\n",
      "AttributeError: module 'numpy.testing._private' has no attribute 'utils'\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7c72fa84f6f74b2c814c1499c92f1e77",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "parsing log, completed traces ::   0%|          | 0/700 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_132914/3486901750.py\", line 67, in <module>\n",
      "    graph = pm4py.discover_dcr_rejection(log, \"Required\", \"Forbidden\", seed=42)\n",
      "  File \"/mnt/c/Users/svorr/Datalogi/REBS/pm4py-dcr/pm4py/discovery.py\", line 977, in discover_dcr_rejection\n",
      "    return dcr_alg.apply(log, dcr_rejection, parameters=properties)\n",
      "  File \"/mnt/c/Users/svorr/Datalogi/REBS/pm4py-dcr/pm4py/algo/discovery/dcr_rejection/algorithm.py\", line 43, in apply\n",
      "    return exec_utils.get_variant(variant).apply(log, parameters=parameters)\n",
      "  File \"/mnt/c/Users/svorr/Datalogi/REBS/pm4py-dcr/pm4py/algo/discovery/dcr_rejection/variants/dcr_rejection.py\", line 44, in apply\n",
      "    return disc.mine(log, parameters = parameters)\n",
      "  File \"/mnt/c/Users/svorr/Datalogi/REBS/pm4py-dcr/pm4py/algo/discovery/dcr_rejection/variants/dcr_rejection.py\", line 76, in mine\n",
      "    self.init(log, parameters)\n",
      "  File \"/mnt/c/Users/svorr/Datalogi/REBS/pm4py-dcr/pm4py/algo/discovery/dcr_rejection/variants/dcr_rejection.py\", line 89, in init\n",
      "    positive = log[log[label_key] == positive_label]\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/frame.py\", line 4093, in __getitem__\n",
      "    return self._getitem_bool_array(key)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/frame.py\", line 4155, in _getitem_bool_array\n",
      "    return self._take_with_is_copy(indexer, axis=0)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/generic.py\", line 4153, in _take_with_is_copy\n",
      "    result = self.take(indices=indices, axis=axis)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/generic.py\", line 4133, in take\n",
      "    new_data = self._mgr.take(\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/internals/managers.py\", line 893, in take\n",
      "    new_labels = self.axes[axis].take(indexer)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/pandas/core/indexes/range.py\", line 1168, in take\n",
      "    ind_max = indices.max()\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/numpy/_core/_methods.py\", line 44, in _amax\n",
      "    return umr_maximum(a, axis, None, out, keepdims, initial, where)\n",
      "TypeError: int() argument must be a string, a bytes-like object or a real number, not '_NoValueType'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2144, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 1088, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 970, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/IPython/core/ultratb.py\", line 792, in lines\n",
      "    return self._sd.lines\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "  File \"/home/chris/miniconda3/envs/gds/lib/python3.10/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import pandas as pd\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "import pm4py\n",
    "from pm4py.util.xes_constants import DEFAULT_TIMESTAMP_KEY \n",
    "\n",
    "def simplify(graph):\n",
    "    to_remove = set()\n",
    "    for event in graph['events']:\n",
    "        has_relations = False\n",
    "        for other in graph['events']:\n",
    "            a = other in graph['conditionsFor'].get(event, set())\n",
    "            b = event in graph['conditionsFor'].get(other, set())\n",
    "            c = other in graph['responseTo'].get(event, set())\n",
    "            d = event in graph['responseTo'].get(other, set())\n",
    "            e = other in graph['excludesTo'].get(event, set())\n",
    "            f = event in graph['excludesTo'].get(other, set())\n",
    "            if a or b or c or d or e or f:\n",
    "                has_relations = True\n",
    "                break\n",
    "\n",
    "        if not has_relations:\n",
    "            to_remove.add(event)\n",
    "\n",
    "    graph['events'] -= to_remove\n",
    "    graph['labels'] -= to_remove\n",
    "    graph['labelMapping'] = {event: event for event in graph['events']}\n",
    "\n",
    "def metrics(graph):\n",
    "    pos = pm4py.conformance_dcr(log[log['case:label'] == \"Required\"], graph)\n",
    "    neg = pm4py.conformance_dcr(log[log['case:label'] == \"Forbidden\"], graph)\n",
    "    TP = sum(1 for trace in pos if trace['is_fit'])\n",
    "    FN = sum(1 for trace in pos if not trace['is_fit'])\n",
    "    TN = sum(1 for trace in neg if not trace['is_fit'])\n",
    "    FP = sum(1 for trace in neg if trace['is_fit'])\n",
    "    \n",
    "    precision = TP / (TP + FP) if (TP + FP) > 0 else 0\n",
    "    recall = TP / (TP + FN) if (TP + FN) > 0 else 0\n",
    "    f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0\n",
    "    accuracy = (TP + TN) / (TP + FP + TN + FN) if (TP + FP + TN + FN) > 0 else 0\n",
    "    \n",
    "    print('True Positive: ', TP)\n",
    "    print('False Negative:', FN)\n",
    "    print('True Negative: ', TN)\n",
    "    print('False Positive:', FP)\n",
    "    print('Accuracy: ', accuracy)\n",
    "    print('Precision:', precision)\n",
    "    print('Recall:   ', recall)\n",
    "    print('F1-Score: ', f1_score)\n",
    "\n",
    "\n",
    "# Other miners and pm4py.conformance_dcr typicaly require a timestamp column.\n",
    "# This is a weird forced requirement, that is rearely used, but often enfored :|\n",
    "log = pm4py.read_xes(\"./Dreyers Foundation.xes\")\n",
    "if True:\n",
    "    if not DEFAULT_TIMESTAMP_KEY in log.columns:\n",
    "        date = datetime(2024, 1, 1, 0, 0, 0)\n",
    "        timestamp = pd.Series([date + timedelta(minutes=i) for i in range(len(log))])\n",
    "        log[DEFAULT_TIMESTAMP_KEY] = pd.to_datetime(timestamp)\n",
    "\n",
    "# Choose whether to run our implementation or the DisCoveR method.\n",
    "if True:\n",
    "    graph = pm4py.discover_dcr_rejection(log, \"Required\", \"Forbidden\", seed=42)\n",
    "else:\n",
    "    graph, _ = pm4py.discover_dcr(log[log['case:label'] == 'Required'])\n",
    "\n",
    "metrics(graph)\n",
    "simplify(graph)\n",
    "pm4py.view_dcr(graph)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gds",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
